---
- hosts: all
  become: true

  vars:
    phab_home: /opt/phacility
    phab: "{{phab_home}}/phabricator"
    repos: "{{phab_home}}/repos"
    files: "{{phab_home}}/files"
    vcs_user: git
    daemon_user: phd
    timezone: Europe/Berlin
    base_uri: http://127.0.0.1:8080/
    # Cheap hack to suppress warning.
    file_uri: http://localhost.localdomain:8080/

    project: "TheProject"
    prototypes: "true"
    imagemagick: "true"
    youtube: "true"
    test_plan: "true"

  tasks:
  - include: task-deps.yml
  - include: task-users.yml
  - include: task-source.yml
  - include: task-mysql.yml
  - include: task-nginx.yml
  - include: task-php.yml
  - include: task-phabricator.yml

  handlers:
  - name: restart mysql
    service: name=mysql state=restarted

  - name: restart nginx
    service: name=nginx state=restarted

  - name: restart fpm
    service: name=php7.1-fpm state=restarted

  - name: restart phabricator
    systemd: name=phabricator-phd daemon_reload=yes state=restarted
